spring:
  application:
    name: swimpool
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/swimpool_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: swimpool
    password: qwer1234!
  mustache:
    suffix: .html
    enabled: true
    charset: UTF-8
    servlet:
      cache: false


server:
  port: 18080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.swimpool
  configuration:
    map-underscore-to-camel-case: true