spring:
  application:
    name: springbootwebpj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://localhost:3306/springboot_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8	# ?????? URL
    username: springbootwebpj_user
    password: springbootwebpj9876$
  mustache:
    suffix: .html
    servlet:
      cache: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.mjc813.springbootwebpj
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8866

